version: '2'

services:
  influxdb:
    image: influxdb:1.2
    volumes:
      - ~/applications/influx:/var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    restart: always
  mim:
    build: .
    ports:
      - "8000:8000"
    restart: always
    
