version: '2'

services:
  influxdb:
    image: influxdb:1.2
    volumes:
      - ~/applications/influx:/var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    restart: always
  mim:
    build: .
    environment:
      - FLASK_DEBUG=1
    volumes:
      - "./src:/app"
    ports:
      - "5000:5000"
    restart: always
    
